version: "3.8"
services:
  otrs:
    restart: always
    container_name: otrs_6.0.23
    build:
      context: ./otrs_install
      dockerfile: otrs.dockerfile
    networks:
      otrs_mysql:
        ipv4_address: 172.21.0.2
    links:
      - "db_mysql"

  db_mysql:
    restart: always
    container_name: db_mysql
    image: mysql:5.7
    command:
      [
        "--default-authentication-plugin=mysql_native_password",
        "--max_allowed_packet=64M",
        "--innodb-log-file-size=256M",
        "--character-set-server=utf8",
        "--collation-server=utf8_unicode_ci",
      ]
    environment:
      MYSQL_ROOT_PASSWORD: "infra"
    networks:
      otrs_mysql:
        ipv4_address: 172.21.0.3

networks:
  otrs_mysql:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.21.0.0/29